### PR TITLE
Lu 2665 calculate means tests

### PR DESCRIPTION
**Pull request by NigelBond**
These changes include the tests for calculate means plus the work on iqrs and atypicals

### CODE REVIEW

**Comment by kingmushroom** [comment]
(only looked at means, iqrs and atyps tested previously)

+ves
Tests pass
Code looks good
Works in AWS

-ves
No Readme
Old commented out code
Some comments no longer apply
Couple of unused imports and variables.

PEP8 -
Very few pep8 issues(but still a few)

**Comment by NigelBond** [comment]
I think Tom should probably do the readme for this as he wrote the method and wrangler. 
Fair point on the commented out code. We didn't want to remove it before consulting with Tom
We missing this but probably the same issue as above - ie need to consult with @thomashenson 
Need more details on the pep8 issues

**Comment by thomashenson** [comment]
I’m doing the readme again as it didn’t save just need to push up.

**Comment by kingmushroom** [comment]
Readme is there now.

Pep8, going to see if i can pull out the inspection results so i dont have to type them all out

**Comment by kingmushroom** [comment]
[means.zip](https://github.com/ONSdigital/es-imputation-sg/files/3355148/means.zip)

Above zip is the pep8 warnings. (very little tbh though, probably took longer to work out how to give you the report)

**Comment by bitmonkey** [comment]
@thomashenson there are merge conflicts with this branch and master, need bring everything up to date and merge master into `lu-2665-calculate-means-tests` and resolve the conflicts.

Pycharm is pretty good for resolving merge conflicts, give me a shout when you're ready to look at this and I'll show you the conflict editor.

**Comment by thomashenson** [comment]
>     1. Still have `flake8` lint errors 💔
> 
> 
> `./do.sh run python flake8 ./*iqrs*.py ./*means*.py ./*atypi*.py ./tests/*iqrs*.py ./tests/*means*.py ./tests/*atypi*.py > flake8_says_no.txt`
> 
> [flake8_says_no.txt](https://github.com/ONSdigital/es-imputation-sg/files/3492330/flake8_says_no.txt)
> 
>     1. Test coverage isn't covering a few of the exception cases:
> 
> 
> ` ./do.sh test --cov --cov-report term-missing ./tests/*iqrs*.py ./tests/*atypic*.py ./tests/*means*.py`
> 
> ```
> Name                          Stmts   Miss  Cover   Missing
> -----------------------------------------------------------
> atypicals_wrangler.py            87      2    98%   152-160
> calculate_means_wrangler.py      88      2    98%   155-163
> iqrs_wrangler.py                 87      2    98%   149-157
> ```
> 
> It looks like it's the cases where you're trapping the `IncompleteReadError`....you might dealing with testing this later in the error handling ticket though so can let this slide 😉

How do I get my flake8 to pick up on these things, e.g. isort, commented out code?

**Comment by thomashenson** [comment]
Hoorah!

**Pull request merged**
